# Generated by Django 4.1.7 on 2023-03-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.CharField(max_length=200, verbose_name='name of the article')),
                ('a_content', models.TextField(verbose_name='articles text')),
                ('a_pub_dt', models.DateTimeField(verbose_name='public date')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_au_name', models.CharField(max_length=50, verbose_name='name of an  author')),
                ('c_content', models.TextField(verbose_name='comments text')),
                ('a_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
