# Generated by Django 4.1.7 on 2023-05-02 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai_15', '0002_alter_question_q_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='q_date_res',
            field=models.DateTimeField(null=True, verbose_name='response date'),
        ),
    ]
